name: Reflect Tests

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR creation and updates

jobs:
  reflect_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Reflect Tests
        env:
          REFLECT_API_TOKEN: ${{ secrets.REFLECT_API_TOKEN }}
        run: |
          # Extract necessary information
          GITHUB_REPO=${{ github.repository }}
          GITHUB_SHA=${{ github.sha }}
          GITHUB_ORG=${GITHUB_REPO%/*}

          # Trigger Reflect Test Suite execution
          curl -X POST "https://api.reflect.io/v1/test-suites/submittal_flow_for_poc/run" \
            -H "Authorization: Bearer $REFLECT_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "repository": "'$GITHUB_REPO'",
              "organization": "'$GITHUB_ORG'",
              "sha": "'$GITHUB_SHA'"
            }'
